[package]
name = "naoqi-ipc"
version = "0.1.0"
authors = ["Lasse Dissing Hansen"]
edition = "2018"

[dependencies]
bincode = "^1.3"
serde = { version = "^1.0", features = ["derive"] }
ipc-channel = "^0.14"
